sudo: required

language: perl6

os:
  - linux
  - osx

perl6:
  - 2016.12
  - latest

install:
  - echo $TRAVIS_OS_NAME
  - rakudobrew build zef
  - zef --depsonly install .
  - zef install Test::META
  - zef build .

script:
    - prove -ve "perl6 -Ilib" t
    - TEST_AUTHOR=1 prove -ve "perl6 -Ilib" t
    - zef install Clean
